import { API_CONFIG } from './api';

export const ENDPOINTS = {
    AUTH: {
        SIGNUP: `${API_CONFIG.AUTH_SERVICE.BASE_URL}${API_CONFIG.AUTH_SERVICE.BASE_PATH}/signup`,
        LOGIN: `${API_CONFIG.AUTH_SERVICE.BASE_URL}${API_CONFIG.AUTH_SERVICE.BASE_PATH}/login`,
        LOGOUT: `${API_CONFIG.AUTH_SERVICE.BASE_URL}${API_CONFIG.AUTH_SERVICE.BASE_PATH}/logout`,
    },
};